# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('HavelCMS', '0002_auto_20150519_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelink',
            name='relatedlink_ptr',
        ),
        migrations.RemoveField(
            model_name='link',
            name='relatedlink_ptr',
        ),
        migrations.RemoveField(
            model_name='relatedlink',
            name='content_type',
        ),
        migrations.AlterModelManagers(
            name='resource',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(blank=True, choices=[(b'pages/index.html', b'StartPage Template'), (b'pages/statement-press.html', b'Statement Press Template'), (b'pages/article_page.html', b'Article page Template'), (b'pages/cms_page.html', b'CMS Template'), (b'pages/search_result.html', b'Search Result Template'), (b'pages/search_tag.html', b'Search Tag Template')], default=None, help_text='Inherit if empty', max_length=100),
        ),
        migrations.DeleteModel(
            name='FileLink',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='RelatedLink',
        ),
    ]
