# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 14:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HavelCMS', '0003_auto_20160229_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
