# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 12:22
from __future__ import unicode_literals

import HavelCMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HavelCMS', '0004_auto_20160229_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_image',
            field=models.ImageField(blank=True, null=True, upload_to=HavelCMS.models.page_image_path, verbose_name='Page image'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=HavelCMS.models.page_image_path, verbose_name='Page mobile image'),
        ),
    ]
