# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HavelCMS', '0005_auto_20160423_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
